### ISSUE TITLE
storyDetail po文時需要一張灰色的預設圖片

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/trademuch#440]

**Comment by chengloria** [comment]
![2016-02-19 09 46 39](https://cloud.githubusercontent.com/assets/16075223/13164137/e3991828-d6ed-11e5-826f-7754198c53f5.png)

**Comment by chengloria** [comment]
![2016-02-22 11 16 23](https://cloud.githubusercontent.com/assets/16075223/13208642/e0d14ace-d955-11e5-91b8-4ee3600d0398.png)
